### ISSUE TITLE
Remove https://github.com/UPPMAX/R-python-julia-matlab-HPC/tree/main/exercises/matlab/MatlabExercises.tar.gz from the link checker ignore file

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/R-python-julia-matlab-HPC#107]
There is a link to https://github.com/UPPMAX/R-python-julia-matlab-HPC/tree/main/exercises/matlab/MatlabExercises.tar.gz . It is good that this link is there. However, the file is not there yet.

To check the link checker, all links need to be valid, hence this file is added to `.leechyignore` (or something). Remove it from there when ready :+1:

**Comment by bclaremar** [comment]
now there is just one tar for all languages
