### ISSUE TITLE
index overview

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/R-python-julia-matlab-HPC#11]

**Comment by bclaremar** [comment]
Anyone can make changes

**Comment by richelbilderbeek** [comment]
I think that [content of the course](https://uppmax.github.io/R-python-julia-HPC/#content-of-the-course) has been a lot of work (and I hope it has been done by a script!). However, due to Sphinx, we have a TOC at the left side of the website already. 

I suggest to remove the section '[content of the course](https://uppmax.github.io/R-python-julia-HPC/#content-of-the-course)'.

I volunteer to do so.

**Comment by bclaremar** [comment]
Don't touch!!!

This IS the structure

**Comment by bclaremar** [comment]
removing it ruins the whole menu!!!

**Comment by bclaremar** [comment]
You can also give a “hidden” option to the directive, like this:

.. toctree::
   :hidden:

   doc_1
   doc_2

This will still notify Sphinx of the document hierarchy, but not insert links into the document at the location of the directive – this makes sense if you intend to insert these links yourself, in a different style, or in the HTML sidebar.

In the end, all documents in the [source directory](https://sphinx-doc-zh.readthedocs.io/en/latest/glossary.html#term-source-directory) (or subdirectories) must occur in some toctree directive; Sphinx will emit a warning if it finds a file that is not included, because that means that this file will not be reachable through standard navigation. Use [unused_docs](https://sphinx-doc-zh.readthedocs.io/en/latest/config.html#confval-unused_docs) to explicitly exclude documents from building, and [exclude_trees](https://sphinx-doc-zh.readthedocs.io/en/latest/config.html#confval-exclude_trees) to exclude whole directories.

**Comment by bclaremar** [comment]
If you want only the titles of documents in the tree to show up, not other headings of the same level, you can use the titlesonly option:

.. toctree::
   :titlesonly:

   foo
   bar

**Comment by bclaremar** [comment]
https://sphinx-doc-zh.readthedocs.io/en/latest/markup/toctree.html

**Comment by richelbilderbeek** [comment]
Ah, I see, well, then let it be I guess :-) . Thanks for enlightening me!

**Comment by bclaremar** [comment]
.. toctree::
:titlesonly:
has been added as mention above!

The Index page now only show the sessions for each lesson, not the level 2 headings
