### ISSUE TITLE
matlab jupyter

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/R-python-julia-matlab-HPC#30]

**Comment by pojeda** [comment]
the setup for matlab+jupyter was added here: https://uppmax.github.io/R-python-julia-matlab-HPC/matlab/interactiveMatlab.html#running-matlab-in-a-jupyter-notebook /Pedro

**Comment by bclaremar** [comment]
Björn added UPPMAX way

**Comment by bclaremar** [comment]
needs update in introduction and keypoints

**Comment by pojeda** [comment]
I updated both.
