### ISSUE TITLE
Improve prerequisites

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/R-python-julia-matlab-HPC#35]
Me and BC volunteered to do so on 2024-09-27.

**Comment by richelbilderbeek** [comment]
I will create a PR from `issue_35_prerequisites` to `develop` that Björn can review ...

**Comment by bclaremar** [comment]
I decided to keep some but modified parts like:
- Get familiar with the Linux/Bash command line
- Get familiar with a text editor on a cluster

**Comment by richelbilderbeek** [comment]
Sure! Looks like this is done :+1:

I've also updated a link to the COSMOS documentation (the LUNARC doc must have been added recently)!
