### ISSUE TITLE
Suggest: 'Common' first in menu

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/R-python-julia-matlab-HPC#37]
Currently, our main menu at the left side of the screen lists 'Common' last:

![Screenshot from 2024-09-27 12-46-14](https://github.com/user-attachments/assets/e5b844eb-74c7-4a88-96d0-71ac6d2dbea1)

I suggest to move it upwards, as it is more important than any specialized section.

**Comment by rlpitts** [comment]
Agreed. I think it should be at the top.

**Comment by bclaremar** [comment]
And then add prereqs here?

**Comment by bclaremar** [comment]
Having the parallelism session in the top, however, disturbs the chronological flow more than having common in the bottom, in my opinion.
Login session feels "common" but should be in the top. 
Prereqs by its own or as part of common?

Not very clear what is the best solution.

**Comment by bclaremar** [comment]
I test the Common and we´ll see if it looks good!

**Comment by bclaremar** [comment]
It's up

**Comment by richelbilderbeek** [comment]
Well done! Let's close this Issue :+1:
