### ISSUE TITLE
revise Syllabus (index.md)

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/R-python-julia-matlab-HPC#38]
- [x] Björn moves login things to login document
- [x] rm CoC
- [x] rm noneeds
- [x] renew cluster figures @bclaremar

**Comment by bclaremar** [comment]
I'll inform you @Richel when done and you can later invite others for input

**Comment by bclaremar** [comment]
@richelbilderbeek: Removal of login stuff is done
The floor is free!

I'll unassign

**Comment by bclaremar** [comment]
Shall I clean and modify the document according to our decisions in the meeting.

**Comment by richelbilderbeek** [comment]
Sure! I'll unassign and put you on it :+1:

**Comment by bclaremar** [comment]
Added back "prepare environment from login" since not everyone will join the login session.
