### ISSUE TITLE
Extra section in the rendered documentation

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/R-python-julia-matlab-HPC#44]
@bclaremar realized that we have missed an Extra material section (present in the HPC-python course https://uppmax.github.io/HPC-python/packages_deeper.html

He thinks it would be nice to have such an area if we feel we want to move some material there

Let's see if anyone uses it but now there is an docs/extra folder with, as of now, just a matlab file.
Some content may fit in one language file with different sections.
Other content may fit better in a methods file, like parallelism paradigms
for instance!

**Comment by richelbilderbeek** [comment]
Yup, let's try this out and see :-) . I won't use it though...

**Comment by bbrydsoe** [comment]
Good idea! I may or may not have something to put there.

**Comment by rlpitts** [comment]
Putting this here partly for my own reference later: if a user needs to make a folder, it'll probably be in either `/lunarc/nobackup/projects/lu20YY-MM-XX/` or the user's home directory.

**Comment by pojeda** [comment]
I agree with that /Pedro
