### ISSUE TITLE
Julia modes is demo:ed already in the introduction

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/R-python-julia-matlab-HPC#46]
Björn thinks that the syntax and demos for the modes in julia in [intro session](https://uppmax.github.io/R-python-julia-matlab-HPC/julia/introJulia.html) can wait until the [load_run](https://uppmax.github.io/R-python-julia-matlab-HPC/julia/load_runJulia.html) session.
Reason: The exercises otherwise asks students to look back to the former session to solve them

**Björn's suggestion:**
Tell in the intro session about the modes and the syntax used.
Björn performs the demo after showing load and start of REPL

**Comment by bclaremar** [comment]
@pojeda Any input to this?

**Comment by pojeda** [comment]
Following upon your thoughts, I think that the demo and the text before the section https://uppmax.github.io/R-python-julia-matlab-HPC/julia/introJulia.html#features-of-julia should be better placed in load_run.  /Pedro

**Comment by bclaremar** [comment]
DONE!
