### ISSUE TITLE
Links @bclaramar needs help with

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/R-python-julia-matlab-HPC#84]
- [404] https://linuxhint.com/gpu-programming-python/ | Failed: Network error: Not Found
- [ERR] https://richelbilderbeek.nl/conda_on_rackham.mp4 | Failed: Network error: error sending request for url (https://richelbilderbeek.nl/conda_on_rackham.mp4)

**Comment by bclaremar** [comment]
All other links, in principle, are working!

**Comment by richelbilderbeek** [comment]
Second is deleted/fixed :-)

**Comment by richelbilderbeek** [comment]
The first page/link simply seems deleted/removed. I suggest to reword to not include a link anymore. I'd volunteer to do so!

**Comment by richelbilderbeek** [comment]
I also removed the other broken link and simply mentioned it is from a now-absent article.

Done!
